#!/bin/bash
LANG=""
local=`pwd`
export LC_NUMERIC=C

for kel in 0.1 2.0 5.0 10.0 100.0 1000.0; do
    for r0 in 1.0; do
        for LadoH in 7.4 7.5 7.6 7.7 7.8 $(seq 8.0 0.5 17.0) $(seq 8.25 0.50 11.75) 12.5 13.5 14.5 15.5 ; do
            for TEMP in $(seq 0.050 0.030 0.500) $(seq 0.540 0.040 0.620) 0.670 0.720 0.800 0.900; do
                if [ -e 'dump_k_'$kel'_r0_'$r0'_L_'$LadoH'_T_'$TEMP'.lammpstrj' ]; then
                   cp 'dump_k_'$kel'_r0_'$r0'_L_'$LadoH'_T_'$TEMP'.lammpstrj' 'dump.lammpstrj'
                   echo $LadoH > inicial_tr
                   ./call < inicial_tr
                   mv 'rdfcm.dat'                                          $local'/rdfcm_k_'$kel'_r0_'$r0'_L_'$LadoH'_T_'$TEMP'.lammpstrj'
                   mv 'dump_cm.lammpstrj'                                  $local'/dump_cm_k_'$kel'_r0_'$r0'_L_'$LadoH'_T_'$TEMP'.lammpstrj'
                fi
            done
        done
    done
done
